spring:
  devtools:
    livereload:
      enabled: true

  config:
    activate:
      on-profile: local

  #h2 DB
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=MYSQL;"
    username: "test"
    password: "test"
    driver-class-name: org.h2.Driver

  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    basic:
      enabled: false