#Devlopment auto restart
spring:
  devtools:
    livereload:
      enabled: true
#h2 db
  datasource:
    url: "jdbc:h2:./testdb"
    username: "test"
    password: "test"
    driver-class-name: org.h2.Driver
#JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
